---
# Service Account for Azure DevOps monitoring deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-devops-sa
  namespace: monitoring
---
# Cluster Role for Azure DevOps monitoring permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-devops-monitoring-role
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - services
  - configmaps
  - persistentvolumeclaims
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Cluster Role Binding for Azure DevOps monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-devops-monitoring-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-devops-monitoring-role
subjects:
- kind: ServiceAccount
  name: azure-devops-sa
  namespace: monitoring
---
# Namespace Role for Azure DevOps monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-devops-monitoring-role
  namespace: monitoring
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - configmaps
  - persistentvolumeclaims
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Role Binding for Azure DevOps monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-devops-monitoring-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azure-devops-monitoring-role
subjects:
- kind: ServiceAccount
  name: azure-devops-sa
  namespace: monitoring 