apiVersion: v1
kind: Service
metadata:
  name: invoiceapi-service-lb
spec:
  type: LoadBalancer
  selector:
    app: invoiceapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: invoiceapi-service
spec:
  selector:
    app: invoiceapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
